{{- range .Values.stages }}
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: {{ .name }}
  namespace: {{ include "kargo-boilerplate.name" $ }}
  annotations: {{ toYaml .annotations | nindent 4 }}
spec:
  requestedFreight: {{ toYaml .requestedFreight | nindent 4 }}
  promotionTemplate: {{ toYaml .promotionTemplate | nindent 4 }}
  {{- with .verification }}
  verification:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}