apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kargo
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/blakepettersson/kargo-boilerplate.git
        revision: main
        files:
          - path: "config/apps/*.yaml"
  template:
    metadata:
      name: 'kargo-{{.appName}}'
    spec:
      project: kargo-project
      source:
        targetRevision: main
        repoURL: https://github.com/blakepettersson/kargo-boilerplate.git
        path: .
      destination:
        name: kargo1
      syncPolicy:
        automated: {}
        retry:
          limit: 5
          backoff:
            duration: 5s
            maxDuration: 3m0s
            factor: 2
        syncOptions:
        - CreateNamespace=true
  templatePatch: |
    spec:
      source:
        helm:
          valuesObject:
            nameOverride: '{{.appName}}'
            warehouse:
              subscriptions:
                - chart:
                    repoURL: '{{.registry}}/{{.chart}}'
                - image:
                    repoURL: '{{.image}}'
            stages:
              - name: dev
                annotations:
                  kargo.akuity.io/color: green
                requestedFreight:
                  - origin:
                      kind: Warehouse
                      name: '{{.appName}}'
                    sources:
                      direct: true
                promotionTemplate:
                  spec:
                    steps:
                      - uses: argocd-update
                        config:
                          apps:
                            - name: '{{.appName}}-dev'
                              sources:
                                - repoURL: '{{.registry}}'
                                  chart: '{{.chart}}'
                                  updateTargetRevision: true
                                  helm:
                                    images:
                                      - image: '{{.image}}'
                                        key: image.tag
                                        value: Tag
              - name: staging
                annotations:
                  kargo.akuity.io/color: yellow
                requestedFreight:
                  - origin:
                      kind: Warehouse
                      name: '{{.appName}}'
                    sources:
                      stages:
                        - dev
                promotionTemplate:
                  spec:
                    steps:
                      - uses: argocd-update
                        config:
                          apps:
                            - name: '{{.appName}}-staging'
                              sources:
                                - repoURL: '{{.registry}}'
                                  chart: '{{.chart}}'
                                  updateTargetRevision: true
                                  helm:
                                    images:
                                      - image: '{{.image}}'
                                        key: image.tag
                                        value: Tag
