apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kargo-stages
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/blakepettersson/kargo-boilerplate.git
              revision: main
              files:
                - path: "config/apps/*.yaml"
          - git:
              repoURL: https://github.com/blakepettersson/kargo-boilerplate.git
              revision: main
              files:
                - path: "config/stages/*.yaml"
  template:
    metadata:
      name: 'kargo-{{.appName}}-stage-{{.stageName}}'
    spec:
      project: kargo-project
      source:
        targetRevision: main
        repoURL: https://github.com/blakepettersson/kargo-boilerplate.git
        path: .
      destination:
        name: kargo1
      syncPolicy:
        automated: {}
        retry:
          limit: 5
          backoff:
            duration: 5s
            maxDuration: 3m0s
            factor: 2
        syncOptions:
        - CreateNamespace=true
  templatePatch: |
    spec:
      source:
        helm:
          valuesObject:
            nameOverride: '{{.appName}}'
            stages:
              - name: '{{.stageName}}'
                annotations:
                  kargo.akuity.io/color: '{{.color}}'
                requestedFreight:
                  - origin:
                      kind: Warehouse
                      name: '{{.appName}}'
                    sources:
                      direct: {{empty .upstreamStages}}
                      {{- if not (empty .upstreamStages) }}
                      stages: {{.upstreamStages}}
                      {{- end }}
                promotionTemplate:
                  spec:
                    steps:
                      - uses: argocd-update
                        config:
                          apps:
                            - name: '{{.appName}}-{{.stageName}}'
                              sources:
                                - repoURL: '{{.registry}}'
                                  chart: '{{.chart}}'
                                  updateTargetRevision: true
                                  helm:
                                    images:
                                      - image: '{{.image}}'
                                        key: image.tag
                                        value: Tag
